# fly.toml app configuration file generated for fullstack-open-cicd on 2023-08-21T13:32:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-open-cicd"
primary_region = "yyz"

# [http_service]
#   internal_port = 5000
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"
  
[[services]]
  http_checks = []
  internal_port = 8080

  processes = ["app"]
